name = "interactions-proxy"
type = "javascript"
zone_id = ""
account_id = ""
route = ""
workers_dev = true

kv_namespaces = [ 
         { binding = "DATA_KV", id = ""}
]

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"
